# Generated by Django 3.2.8 on 2021-12-22 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_house'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='purpose',
            field=models.CharField(blank=True, choices=[('RENT', 'RENT'), ('SELL', 'SELL')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='images',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
