# Generated by Django 3.2.8 on 2021-12-24 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_house_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='images',
        ),
        migrations.CreateModel(
            name='ImageForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images', verbose_name='Image')),
                ('house', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='authentication.house')),
            ],
        ),
    ]
