# Generated by Django 3.2.8 on 2021-12-24 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_auto_20211224_1423'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImageForm',
            new_name='Image',
        ),
    ]
