# Generated by Django 3.2.8 on 2021-12-27 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_rename_imageform_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='address',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
