# Generated by Django 3.2.8 on 2021-12-28 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_auto_20211227_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='address',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
